spring:
  application:
    name: Eventoria
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false

  profiles:
    active: dev

app:
  jwt:
    ExpirationMs: ${JWT_EXPIRATION_IN_MS}
    RefreshExpirationMs: ${JWT_REFRESH_EXPIRATION_IN_MS}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,caches



