spring:
  application:
    name: Eventoria
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false

  profiles:
    active: dev

  cache:
    caffeine:
        spec: maximumSize=500,expireAfterAccess=30m,recordStats
        cache-names: userCache, eventCache, eventTypeCache, eventCategoryCache, eventStatusCache
  jackson:
    serialization:
      fail-on-empty-beans: false

app:
  jwt:
    ExpirationMs: ${JWT_EXPIRATION_IN_MS}
    RefreshExpirationMs: ${JWT_REFRESH_EXPIRATION_IN_MS}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,caches



springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    filter: true
    persist-authorization: true
    display-request-duration: true
    try-it-out-enabled: true
    syntax-highlight:
      activate: true
      theme: obsidian
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Eventoria API
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.giftedlabs.eventoria
  cache:
    disabled: false
  show-actuator: true


openapi:
  dev-url: http://localhost:5000
  prod-url: https://api.eventoria.com
